backend:
  name: git-gateway
  branch: main

media_folder: "_site/images/uploads"
public_folder: "/images/uploads"
locale: "fr"
publish_mode: editorial_workflow
collections: 
  - name: "posts"
    label: "Posts"
    folder: "posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "desccription", widget: "string"}
      - {label: "Post Body", name: "body", widget: "markdown"}
      - {label: "Date", name: "date", widget:"date", default: ""}
      - {label: "FeaturedImage", name: "featuredImage", widget: "image"}